baseURL = ""
languageCode = "en-us"
title = "Grynn Website"
theme = "vinayak"



[menu]

  [[menu.main]]
    identifier = "CARRERS"
    name = "CARRERS"
    title = "CARRERS"
    pre = ""
    url = "/careers"
    weight = -160

  [[menu.main]]
    identifier = "CONTACT"
    name = "CONTACT"
    title = "CONTACT"
    url = "/contact"
    weight = -150

  [[menu.main]]
    identifier = "BLOG"
    name = "BLOG"
    title = "BLOG"
    url = "/blog"
    weight = -140

  [[menu.main]]
    identifier = 	"ERPNEXT"
    name = 		"ERPNEXT"
    title = 		"ERPNEXT"
    pre = 		""
    url = 		"/erpnext"
    weight = 		-170

  [[menu.main]]
    parent = 		"ERPNEXT"
    identifier = 	"WHY ERPNEXT"
    name = 		"WHY ERPNEXT"
    title = 		"WHY ERPNEXT"
    pre = 		""
    url = 		"/why-erpnext"
    weight = 		-171

  [[menu.main]]
    identifier = 	"OUR OFFERS"
    name = 		"OUR OFFERS"
    title = 		"OUR OFFERS"
    pre = 		""
    url = 		"/our-offers"
    weight = 		-190

  [[menu.main]]
    parent = 		"OUR OFFERS"
    identifier = 	"GRYNN BUY"
    name = 		"GRYNN BUY"
    title = 		"GRYNN BUY"
    url = 		"/our-offers/buy"
    weight = 		-185


